function  [sumFt, sumFt2, sumOM, sumOM2, sumST, sumST2,...
    sumBeta, sumBeta2, sumObsVariance, sumObsVariance2,...
    sumFactorVar, sumFactorVar2,sumVarianceDecomp,...
    sumVarianceDecomp2, ml] = Mldfvar(yt, Xt,  InfoCell, Sims,...
    burnin, ReducedRuns, initFactor, initBeta, initobsmodel,...
    initStateTransitions, v0, r0, s0, d0, identification, estML, varargin)

if nargin <= 16
    [sumFt, sumFt2, sumOM, sumOM2, sumST, sumST2,...
        sumBeta, sumBeta2, sumObsVariance, sumObsVariance2,...
        sumFactorVar, sumFactorVar2,sumVarianceDecomp,...
        sumVarianceDecomp2, ml] = ...
        NoBlocks(yt, Xt,  InfoCell, Sims,...
        burnin, ReducedRuns, initFactor, initBeta, initobsmodel,...
        initStateTransitions, v0, r0, s0, d0, identification, estML);
else
    %      [sumFt, sumFt2, sumOM, sumOM2, sumST, sumST2,...
    %     sumBeta, sumBeta2, sumObsVariance, sumObsVariance2,...
    %     sumFactorVar, sumFactorVar2,sumVarianceDecomp,...
    %     sumVarianceDecomp2, ml] =...
    %     Blocks(yt, Xt,  InfoCell, Sims,...
    %     burnin, ReducedRuns, initFactor, initBeta, initobsmodel,...
    %     initStateTransitions, v0, r0, s0, d0, identification, estML, varargin{1},...
    %     varargin{2});
    [sumFt, sumFt2, sumOM, sumOM2, sumST, sumST2,...
        sumObsVariance, sumObsVariance2,...
        sumFactorVar, sumFactorVar2,sumVarianceDecomp,...
        sumVarianceDecomp2, ml] = ...
        MultDyFacVarSimVersion(yt, InfoCell, Sims,...
        burnin, ReducedRuns, initFactor, initobsmodel, initStateTransitions,...
        v0, r0, s0,d0, identification, estML);
end
end

