function [xt, lastMean, lastCovar] = ...
    optimizeA(x0, ydemut, obsPrecision, factor,factorPrecision,...
    lastMean, lastCovar, options, identification, breakUp, x1)


[xt, lastMean, lastCovar] = identification2(x0, ydemut, obsPrecision, factor, factorPrecision,...
    lastMean, lastCovar, options, x1);

end