function [] = kowCompare(Sims,burnin,ReducedRuns)
if ischar(Sims)
    Sims = str2num(Sims);
end
if ischar(burnin)
    burnin = str2num(burnin);
end
if ischar(ReducedRuns)
    ReducedRuns = str2num(ReducedRuns);
end
load('kowperiod1.mat')
[sumFt1, sumFt21, storeBeta1, storeObsVariance1, storeObsModel1,...
    storeStateTransitions1, ml1] = ...
    kowMultiLevelFactor(yt, Xt, RegionIndices,...
      CountriesThatStartRegions, Countries, SeriesPerCountry,...
      Sims, burnin, blocks,  RegionBlocks, K/RegionBlocks, initBeta, initobsmod, initGamma, v0, r0, ...
      ReducedRuns);
load('kowperiod2.mat')
[sumFt2, sumFt22, storeBeta2, storeObsVariance2, storeObsModel2,...
    storeStateTransitions2, ml2] = ...
    kowMultiLevelFactor(yt, Xt, RegionIndices,...
      CountriesThatStartRegions, Countries, SeriesPerCountry,...
      Sims, burnin, blocks,  RegionBlocks, K/RegionBlocks, initBeta, initobsmod, initGamma, v0, r0, ...
      ReducedRuns);  
  load('kowfull.mat')
  [sumFt3, sumFt23, storeBeta3, storeObsVariance3, storeObsModel3,...
    storeStateTransitions3, ml3] = ...
    kowMultiLevelFactor(yt, Xt, RegionIndices,...
      CountriesThatStartRegions, Countries, SeriesPerCountry,...
      Sims, burnin, blocks,  RegionBlocks, K/RegionBlocks, initBeta, initobsmod, initGamma, v0, r0, ...
      ReducedRuns);
  ml1 + ml2
  ml3
  fname = createDateString('comparison_')
  save(fname)
end

