function [sumFt,sumFt2, sumResiduals2, storeFt, storeBeta,...
 storeObsVariance, storeObsModel, storeStateTransitions,...
 zeroOutWorld, zeroOutRegion, zeroOutCountry, sumLastMeanCountry, ...
sumLastMeanRegion, sumLastMeanWorld, sumLastHessianCountry,...
 sumLastHessianRegion, sumLastHessianWorld] =...
    kowMakeStorageContainers(Sims,burnin, betaDim,...
        NumberYequations, NumberTimePeriods,NumberOfFactors,...
        SeriesPerCountry,Countries, EqnsPerBlock, blocks, IRegion, ICountry, Regions)
sumFt = zeros(NumberOfFactors, NumberTimePeriods);
sumFt2 = sumFt;
sumResiduals2 = zeros(NumberYequations,1);
storeFt = zeros(NumberOfFactors,NumberTimePeriods, Sims-burnin);
storeBeta = zeros(betaDim, Sims -burnin);
storeObsVariance = zeros(NumberYequations,Sims -burnin);
storeObsModel = zeros(NumberYequations, 3, Sims-burnin);
storeStateTransitions = zeros(NumberOfFactors, 1, Sims-burnin);
zeroOutWorld = zeros(NumberYequations, 1);
zeroOutRegion = zeros(size(IRegion));
zeroOutCountry = zeros(size(ICountry));
sumLastMeanCountry = zeros(SeriesPerCountry, Countries);
sumLastMeanRegion = zeros(NumberYequations/Regions, Regions);
sumLastMeanWorld = zeros(EqnsPerBlock, blocks);
sumLastHessianCountry = reshape(repmat(eye(SeriesPerCountry), 1, Countries), ...
    SeriesPerCountry, SeriesPerCountry, Countries);
sumLastHessianRegion = reshape(repmat(eye(NumberYequations/Regions), 1, Regions),...
    NumberYequations/Regions,NumberYequations/Regions , Regions);
sumLastHessianWorld = reshape(repmat(eye(EqnsPerBlock),1,blocks), EqnsPerBlock,...
    EqnsPerBlock, blocks);

end

