function probity = import_probity(dataLines)
%IMPORTFILE Import data from a text file
%  PROBITY = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  PROBITY = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  probity = importfile("/home/precision/GoogleDrive/Datasets/ExcessReturns/probity.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Aug-2020 21:00:38

%% Input handling
filename = '/home/precision/GoogleDrive/Datasets/ExcessReturns/probity.csv';
% If dataLines is not specified, define defaults
if nargin < 1
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Date", "p_cons_stap", "p_cons_disc", "p_cons_serv", "p_ener", "p_fina", "p_heal", "p_indu", "p_mate", "p_real", "p_tech", "p_util"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Date", "InputFormat", "yyyy-MM-dd");

% Import the data
probity = readtable(filename, opts);

end