%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/dillon/GoogleDrive/Datasets/rental_data.csv
%
% Auto-generated by MATLAB on 04-Oct-2020 18:58:04

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["RENT", "NO", "RM", "SEX", "DIST", "RPP"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
rentaldata = readtable("/home/dillon/GoogleDrive/Datasets/rental_data.csv", opts);


%% Clear temporary variables
clear opts