%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/precision/GoogleDrive/Datasets/ExcessReturns/spy.csv
%
% Auto-generated by MATLAB on 11-Jun-2020 13:38:48

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Date", "Services", "Discretionary", "Staples", "Energy", "Financials", "Health", "Industrials", "Materials", "RealEstate", "Tech", "Utilities"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Date", "InputFormat", "yyyy-MM-dd");

% Import the data
spy = readtable("/home/precision/GoogleDrive/Datasets/ExcessReturns/probity.csv", opts);


%% Clear temporary variables
clear opts
