%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/precision/GoogleDrive/Datasets/ExcessReturns/probity.csv
%
% Auto-generated by MATLAB on 11-Jun-2020 16:10:20

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["spyDate21246", "p_cons_stap", "p_cons_disc", "p_cons_serv", "p_ener", "p_fina", "p_heal", "p_indu", "p_mate", "p_real", "p_tech", "p_util"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "spyDate21246", "InputFormat", "yyyy-MM-dd");

% Import the data
probity = readtable("/home/precision/GoogleDrive/Datasets/ExcessReturns/probity.csv", opts);


%% Clear temporary variables
clear opts