library(readxl)
pwt90 <- read_excel("~/GoogleDrive/Datasets/pwt90.xlsx", 
                          sheet = "Data")
KOW <- cbind(pwt90[pwt90$countrycode == 'USA' & pwt90$year >= 1960, c('year', 'rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'CAN' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],          
             pwt90[pwt90$countrycode == 'MEX' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'AUS' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'NZL' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'CRI' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'DOM' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'SLV' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'GTM' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'HND' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'JAM' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'PAN' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'TTO' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'ARG' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'BOL' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'BRA' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'CHL' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'COL' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'ECU' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'PRY' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'PER' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'URY' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'VEN' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'FRA' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'AUT' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'BEL' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'DNK' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'FIN' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'DEU' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'GRC' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'ISL' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'IRL' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'ITA' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'LUX' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'NLD' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'NOR' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'PRT' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'ESP' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'SWE' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'CHE' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'GBR' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'CMR' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'CIV' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'KEN' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'MAR' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'SEN' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'ZAF' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'ZWE' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'BGD' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'IND' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'IDN' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'PAK' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'PHL' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'LKA' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'HKG' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'JPN' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'KOR' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'MYS' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'SGP' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')],
             pwt90[pwt90$countrycode == 'THA' & pwt90$year >= 1960, c('rgdpna', 'rconna', 'rkna')])

remove(pwt90)
colnames(KOW) <- c('year', 'rgdpnaUSA', 'rconnaUSA', 'rknaUSA',
  'rgdpnaCAN', 'rconnaCAN', 'rknaCAN',
  'rgdpnaMEX', 'rconnaMEX', 'rknaMEX',
  'rgdpnaAUS', 'rconnaAUS', 'rknaAUS',
  'rgdpnaNZL', 'rconnaNZL', 'rknaNZL',
  'rgdpnaCRI', 'rconnaCRI', 'rknaCRI',
  'rgdpnaDOM', 'rconnaDOM', 'rknaDOM',
  'rgdpnaSLV', 'rconnaSLV', 'rknaSLV',
  'rgdpnaGTM', 'rconnaGTM', 'rknaGTM',
  'rgdpnaHND', 'rconnaHND', 'rknaHND',
  'rgdpnaJAM', 'rconnaJAM', 'rknaJAM',
  'rgdpnaPAN', 'rconnaPAN', 'rknaPAN',
  'rgdpnaTTO', 'rconnaTTO', 'rknaTTO',
  'rgdpnaARG', 'rconnaARG', 'rknaARG',
  'rgdpnaBOL', 'rconnaBOL', 'rknaBOL',
  'rgdpnaBRA', 'rconnaBRA', 'rknaBRA',
  'rgdpnaCHL', 'rconnaCHL', 'rknaCHL',
  'rgdpnaCOL', 'rconnaCOL', 'rknaCOL',
  'rgdpnaECU', 'rconnaECU', 'rknaECU',
  'rgdpnaPRY', 'rconnaPRY', 'rknaPRY',
  'rgdpnaPER', 'rconnaPER', 'rknaPER',
  'rgdpnaURY', 'rconnaURY', 'rknaURY',
  'rgdpnaVEN', 'rconnaVEN', 'rknaVEN',
  'rgdpnaFRA', 'rconnaFRA', 'rknaFRA',
  'rgdpnaAUT', 'rconnaAUT', 'rknaAUT',
  'rgdpnaBEL', 'rconnaBEL', 'rknaBEL',
  'rgdpnaDNK', 'rconnaDNK', 'rknaDNK',
  'rgdpnaFIN', 'rconnaFIN', 'rknaFIN',
  'rgdpnaDEU', 'rconnaDEU', 'rknaDEU',
  'rgdpnaGRC', 'rconnaGRC', 'rknaGRC',
  'rgdpnaISL', 'rconnaISL', 'rknaISL',
  'rgdpnaIRL', 'rconnaIRL', 'rknaIRL',
  'rgdpnaITA', 'rconnaITA', 'rknaITA',
  'rgdpnaLUX', 'rconnaLUX', 'rknaLUX',
  'rgdpnaNLD', 'rconnaNLD', 'rknaNLD',
  'rgdpnaNOR', 'rconnaNOR', 'rknaNOR',
  'rgdpnaPRT', 'rconnaPRT', 'rknaPRT',
  'rgdpnaESP', 'rconnaESP', 'rknaESP',
  'rgdpnaSWE', 'rconnaSWE', 'rknaSWE',
  'rgdpnaCHE', 'rconnaCHE', 'rknaCHE',
  'rgdpnaGBR', 'rconnaGBR', 'rknaGBR',
  'rgdpnaCMR', 'rconnaCMR', 'rknaCMR',
  'rgdpnaCIV', 'rconnaCIV', 'rknaCIV',
  'rgdpnaKEN', 'rconnaKEN', 'rknaKEN',
  'rgdpnaMAR', 'rconnaMAR', 'rknaMAR',
  'rgdpnaSEN', 'rconnaSEN', 'rknaSEN',
  'rgdpnaZAF', 'rconnaZAF', 'rknaZAF',
  'rgdpnaZWE', 'rconnaZWE', 'rknaZWE',
  'rgdpnaBGD', 'rconnaBGD', 'rknaBGD',
  'rgdpnaIND', 'rconnaIND', 'rknaIND',
  'rgdpnaIDN', 'rconnaIDN', 'rknaIDN',
  'rgdpnaPAK', 'rconnaPAK', 'rknaPAK',
  'rgdpnaPHL', 'rconnaPHL', 'rknaPHL',
  'rgdpnaLKA', 'rconnaLKA', 'rknaLKA',
  'rgdpnaHKG', 'rconnaHKG', 'rknaHKG',
  'rgdpnaJPN', 'rconnaJPN', 'rknaJPN',
  'rgdpnaKOR', 'rconnaKOR', 'rknaKOR',
  'rgdpnaMYS', 'rconnaMYS', 'rknaMYS',
  'rgdpnaSGP', 'rconnaSGP', 'rknaSGP',
  'rgdpnaTHA', 'rconnaTHA', 'rknaTHA')

KOW <- log(KOW[2:55,2:181]) - log(KOW[1:54, 2:181])
KOWrescaled <- KOW*100


write.csv(KOW, '~/GoogleDrive/Datasets/kow_march6.csv', row.names = FALSE)
write.csv(KOWrescaled, '~/GoogleDrive/Datasets/kow_march6_rescaled.csv', row.names = FALSE)
