library(readxl)
pwtd90 <- read_excel("/home/precision/GoogleDrive/Datasets/na_data.xlsx", 
                    sheet = "Data")
KOW <- cbind(pwtd90[pwtd90$countrycode == 'USA' & pwtd90$year >= 1960, c('year', 'q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'CAN' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],          
             pwtd90[pwtd90$countrycode == 'MEX' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'AUS' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'NZL' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'CRI' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'DOM' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'SLV' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'GTM' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'HND' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'JAM' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'PAN' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'TTO' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'ARG' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'BOL' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'BRA' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'CHL' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'COL' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'ECU' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'PRY' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'PER' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'URY' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'VEN' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'FRA' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'AUT' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'BEL' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'DNK' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'FIN' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'DEU' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'GRC' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'ISL' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'IRL' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'ITA' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'LUX' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'NLD' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'NOR' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'PRT' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'ESP' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'SWE' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'CHE' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'GBR' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'CMR' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'CIV' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'KEN' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'MAR' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'SEN' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'ZAF' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'ZWE' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'BGD' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'IND' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'IDN' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'PAK' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'PHL' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'LKA' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'HKG' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'JPN' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'KOR' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'MYS' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'SGP' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')],
             pwtd90[pwtd90$countrycode == 'THA' & pwtd90$year >= 1960, c('q_gdp', 'q_c', 'q_i')])
remove(pwtd90)
colnames(KOW) <- c('year', 'gdpUSA', 'conUSA', 'investUSA',
                   'gdpCAN', 'conCAN', 'investCAN',
                   'gdpMEX', 'conMEX', 'investMEX',
                   'gdpAUS', 'conAUS', 'investAUS',
                   'gdpNZL', 'conNZL', 'investNZL',
                   'gdpCRI', 'conCRI', 'investCRI',
                   'gdpDOM', 'conDOM', 'investDOM',
                   'gdpSLV', 'conSLV', 'investSLV',
                   'gdpGTM', 'conGTM', 'investGTM',
                   'gdpHND', 'conHND', 'investHND',
                   'gdpJAM', 'conJAM', 'investJAM',
                   'gdpPAN', 'conPAN', 'investPAN',
                   'gdpTTO', 'conTTO', 'investTTO',
                   'gdpARG', 'conARG', 'investARG',
                   'gdpBOL', 'conBOL', 'investBOL',
                   'gdpBRA', 'conBRA', 'investBRA',
                   'gdpCHL', 'conCHL', 'investCHL',
                   'gdpCOL', 'conCOL', 'investCOL',
                   'gdpECU', 'conECU', 'investECU',
                   'gdpPRY', 'conPRY', 'investPRY',
                   'gdpPER', 'conPER', 'investPER',
                   'gdpURY', 'conURY', 'investURY',
                   'gdpVEN', 'conVEN', 'investVEN',
                   'gdpFRA', 'conFRA', 'investFRA',
                   'gdpAUT', 'conAUT', 'investAUT',
                   'gdpBEL', 'conBEL', 'investBEL',
                   'gdpDNK', 'conDNK', 'investDNK',
                   'gdpFIN', 'conFIN', 'investFIN',
                   'gdpDEU', 'conDEU', 'investDEU',
                   'gdpGRC', 'conGRC', 'investGRC',
                   'gdpISL', 'conISL', 'investISL',
                   'gdpIRL', 'conIRL', 'investIRL',
                   'gdpITA', 'conITA', 'investITA',
                   'gdpLUX', 'conLUX', 'investLUX',
                   'gdpNLD', 'conNLD', 'investNLD',
                   'gdpNOR', 'conNOR', 'investNOR',
                   'gdpPRT', 'conPRT', 'investPRT',
                   'gdpESP', 'conESP', 'investESP',
                   'gdpSWE', 'conSWE', 'investSWE',
                   'gdpCHE', 'conCHE', 'investCHE',
                   'gdpGBR', 'conGBR', 'investGBR',
                   'gdpCMR', 'conCMR', 'investCMR',
                   'gdpCIV', 'conCIV', 'investCIV',
                   'gdpKEN', 'conKEN', 'investKEN',
                   'gdpMAR', 'conMAR', 'investMAR',
                   'gdpSEN', 'conSEN', 'investSEN',
                   'gdpZAF', 'conZAF', 'investZAF',
                   'gdpZWE', 'conZWE', 'investZWE',
                   'gdpBGD', 'conBGD', 'investBGD',
                   'gdpIND', 'conIND', 'investIND',
                   'gdpIDN', 'conIDN', 'investIDN',
                   'gdpPAK', 'conPAK', 'investPAK',
                   'gdpPHL', 'conPHL', 'investPHL',
                   'gdpLKA', 'conLKA', 'investLKA',
                   'gdpHKG', 'conHKG', 'investHKG',
                   'gdpJPN', 'conJPN', 'investJPN',
                   'gdpKOR', 'conKOR', 'investKOR',
                   'gdpMYS', 'conMYS', 'investMYS',
                   'gdpSGP', 'conSGP', 'investSGP',
                   'gdpTHA', 'conTHA', 'investTHA')
LogFirstDif <- log(KOW[2:55,2:181]) - log(KOW[1:54, 2:181])
KOW <- cbind(KOW$year[2:55], LogFirstDif)
colnames(KOW)[1] <- 'year'

write.csv(KOW, '/Users/dillonflannery-valadez/Google\ Drive/Datasets/kowdetaildata.csv', row.names = FALSE)
