library(xts)
GS10 <- read.csv("~/Datasets/GS10.csv")
GS10$DATE <- as.Date(GS10$DATE)
xtsframe <- xts(x=GS10$GS10, order.by=GS10$DATE)
data <- as.data.frame(to.quarterly(xtsframe))
X <- as.character(rownames(data))
Y <- as.numeric(data[,1])
out <- as.data.frame(cbind(X,Y))
colnames(out) <- c("Date", "gs10")
write.csv(out, "~/Datasets/gs10quarterly.csv", row.names=FALSE)

realgdp <- read.csv("~/Datasets/A191RO1Q156NBEA.csv")
colnames(realgdp) <- c("DATE", "realgdp")
write.csv(realgdp, "~/Datasets/realgpd.csv", row.names=FALSE)

UNRATE <- read.csv("~/Datasets/UNRATE.csv")
UNRATE$DATE <- as.Date(UNRATE$DATE)
xtsframe <- xts(x=UNRATE$UNRATE, order.by=UNRATE$DATE)
data <- as.data.frame(to.quarterly(xtsframe))
X <- as.character(rownames(data))
Y <- as.numeric(data[,1])
out <- as.data.frame(cbind(X,Y))
colnames(out) <- c("Date", "unrate")
write.csv(out, "~/Datasets/unratequarterly.csv", row.names=FALSE)

CPIAUCSL <- read.csv("~/Datasets/CPIAUCSL.csv")
CPIAUCSL$DATE <- as.Date(CPIAUCSL$DATE)
xtsframe <- xts(x=CPIAUCSL$CPIAUCSL, order.by=CPIAUCSL$DATE)
data <- as.data.frame(to.quarterly(xtsframe))
X <- as.character(rownames(data))
Y <- as.numeric(data[,1])
out <- as.data.frame(cbind(X,Y))
colnames(out) <- c("Date", "cpi")
write.csv(out, "~/Datasets/cpiquarterly.csv", row.names=FALSE)

